version: '3.3'

configs:
  logstash.conf:
    file: /docker/configs/logstash.conf

volumes:
  logstashpipeline:

services:
  logstash:
    image: logstash:7.5.1
    hostname: logstash
    environment:
      - 'path.config=/usr/share/logstash/conf/logstash.conf'
      - 'xpack.monitoring.elasticsearch.url='
      - 'xpack.monitoring.enabled=true'
      - 'xpack.monitoring.elasticsearch.username='
      - 'xpack.monitoring.elasticsearch.password='
      - 'TZ=Europe/London'
    configs:
      - source: logstash.conf
        target: /usr/share/logstash/conf/logstash.conf
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 12201:12201/udp    # Logstash will listen on port 12201 for log data from the Docker 'gelf' logging driver
    volumes:
      - logstashpipeline:/usr/share/logstash/pipeline/

